- hosts: master,workers
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_master.yml
   - vars/var_workers.yml
  vars:
     open_firewall: true
     disable_firewall: false
  roles:
    - install_spark
    - install_flume
